### ISSUE TITLE
Sprint1: Sprint Grooming

### ISSUE THREAD

**Issue by akannika** [akannika/Team-3-TCSS-450#13]
As a developer team, we want to have a Sprint Grooming Document so that we can take the Sprint Grooming meeting note and all user stories for Sprint2.

- [x] Create a google doc for Sprint Grooming notes and share it with the team.
- [x] Prepare some user stories for the Backlog Grooming meeting
- [x] Make sure all user stories cover all requirements for Sprint 2
- [x] Write the meeting notes.

**Comment by akannika** [comment]
Update: From the lecture, we will use "Lab 5 - Implementing Push messaging from Web Service" for Sprint 2.

**Comment by S2Mazino** [comment]
Created all epics, still need to break them down to create user stories

**Comment by akannika** [comment]
https://docs.google.com/document/d/1coCKpj2Tf0BtDEy6-58-M7PbSDt10hvU3fLF30xxSEo/edit
