### ISSUE TITLE
Register - Button

### ISSUE THREAD

**Issue by akannika** [akannika/Team-3-TCSS-450#39]
As a user, I want to see the register button so that when I click register, I will get the verification email to verify my account. Maybe get the code to fill in the application or the link to click to verify the email.

- [x] Register - Button - The user can click to send the verification email to the user's email
- [x] Register - Button - Navigate to the code verification fragment --> #40 
- [x] Register - Button - all classes include customized class level and method level JavaDoc
- [x] Register - Button - all classes use constant, contextual naming conventions for classes, methods, and all variable types

**Comment by S2Mazino** [comment]
Changed "The user can click to send the verification code to the user's email" to "verification email to user"
