### ISSUE TITLE
Email Verification - Create the Verification Fragment

### ISSUE THREAD

**Issue by akannika** [akannika/Team-3-TCSS-450#40]
As a developer team, we want to ensure that the user who creates/tries to access the account can access the email they used to create/access the account. 

- [ ] Email Verification - type bar to fill in the code
- [ ] Email Verification - button to click to verify
- [ ] Email Verification - check if the code match
- [ ] Email Verification - navigate to the login page #43 
- [ ] Email Verification - all classes include customized class level and method level JavaDoc
- [ ] Email Verification - all classes use constant, contextual naming conventions for classes, methods, and all variable types

**Comment by S2Mazino** [comment]
Changed to email verification, no longer need this fragment
