### ISSUE TITLE
Login - Look and Feel

### ISSUE THREAD

**Issue by S2Mazino** [akannika/Team-3-TCSS-450#68]
As the developer, I want my application be attractive and easy to use so that the user will want to comeback/use our application.

- [ ] Login - Look and Feel - add the theme/background/color/text/blog to make the application attractive
- [ ] Login - Look and Feel - ensure that our application have the consistency look and feel for the whole app.
- [ ] Login - Look and Feel - all classes include customized class level and method level JavaDoc
- [ ] Login - Look and Feel - all classes use constant, contextual naming conventions for classes, methods, and all variable types

**Comment by akannika** [comment]
Look and Fell for sprin2 is done
