### ISSUE TITLE
Home/Landing page - Display/changeable icon/picture

### ISSUE THREAD

**Issue by S2Mazino** [akannika/Team-3-TCSS-450#75]
As a user, I want to be able to add my picture or have some icon so that I can change my display picture/icon.

- [ ] Home/Landing page - display Nickname - changeable image feature
- [ ] Home/Landing page - display Nickname - display the picture from the database or display the default icon, for example, display the icon with the initial letter of the user first name 
- [ ] Home/Landing page - display Nickname - all classes include customized class level and method level JavaDoc
- [ ] Home/Landing page - display Nickname - all classes use constant, contextual naming conventions for classes, methods, and all variable types

**Comment by akannika** [comment]
We will don't implement this in this project
