### ISSUE TITLE
Home/Landing page - Look and Feel

### ISSUE THREAD

**Issue by S2Mazino** [akannika/Team-3-TCSS-450#77]
As the developer, I want my application be attractive and easy to use so that the user will want to comeback/use our application.

- [x] Home/Landing page - add the theme/background/color/text/blog to make the application attractive
- [x] Home/Landing page- Look and Feel - ensure that our application have the consistency look and feel for the whole app.
- [x] Home/Landing page- Look and Feel - all classes include customized class level and method level JavaDoc
- [x] Home/Landing page- Look and Feel - all classes use constant, contextual naming conventions for classes, methods, and all variable types

**Comment by akannika** [comment]
Look and feel for sprint2 is done
